 Kubermatic Enterprise Read-Only License
#                       Version 1.0 ("KERO-1.0”)
#                   Copyright © 2024 Kubermatic GmbH
#
# 1.	You may only view, read and display for studying purposes the source
#    code of the software licensed under this license, and, to the extent
#    explicitly provided under this license, the binary code.
# 2.	Any use of the software which exceeds the foregoing right, including,
#    without limitation, its execution, compilation, copying, modification
#    and distribution, is expressly prohibited.
# 3.	THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# END OF TERMS AND CONDITIONS
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: aikit
spec:
  description: AIKit is a comprehensive platform to quickly get started to host, deploy, build and fine-tune large language models (LLMs).
  method: helm
  versions:
    - template:
        source:
          helm:
            chartName: aikit/aikit
            chartVersion: 0.1.0
            url: https://sozercan.github.io/aikit/charts
      version: v0.16.0
  defaultValues:
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      # The namespace where Prometheus expects to find the serviceMonitor
      # namespace: ""
    grafanaDashboard:
      enabled: false
      # The namespace where Grafana expects to find the dashboard
      # namespace: ""
      folder:
        annotation: grafana_folder
        name: ai
      label:
        key: grafana_dashboard_aikit
        value: "1"
    defaultValuesBlock: |
      server:
        service:
          # To Expose AIKit externally without ingress, set service type as "LoadBalancer". Default value is "ClusterIP".
          type: "LoadBalancer"
